export default constants = {
  IC_MATERIAL: 'Material',
  IC_MATERIAL_COMMUNITY: 'Material Community',
  IC_FNT_AWESOME: 'FontAwesome',
  IC_IONiCONS: 'ionIcons',
  IC_FONTISTO: 'Fontisto',
  IC_FEATHER: 'Feather',
  IC_OCTICONS: 'Octions',

  NO_INTERNET: 'No Internet',
  INTERNET_ACCESS_ERROR: 'Please check your internet connection',
  NO_INTERNET_SNACKBAR_MESSAGE: 'Internet not available',
  UNKNOWN_ERROR: 'Error Detected',
  UNKNOWN_ERROR_MESSAGE: 'There was an error',

  NO_DATA_FOUND: 'OOOPSS!',
  NO_DATA_FOUND_Message: 'No data found',


  TXT_MOBILE_NUMBER: 'Mobile Number',
  TXT_DOCTOR_REGISTRATION_NO: 'Enter Registration Number',
  TXT_EMAIL_ADDRESS: 'Email',
  TXT_NOT_SIGNED_UP: "Haven't signed up yet?",
  TXT_SIGN_UP: 'Sign Up',
  TXT_FIRST_NAME: 'First Name',
  TXT_LAST_NAME: 'Last Name',
  TXT_STORE_NAME: 'Store Name',
  TXT_ADDRESS: 'Address',
  TXT_CITY: 'City',
  TXT_PINCODE: 'Pincode',
  TXT_STATE: 'State',
  TXT_COUNTRY: 'Country',
  TXT_DOMAIN: 'Domain',
  TXT_CATEGORY: 'Category',
  TXT_FACEBOOK: 'Facebook',
  TXT_LINKEDIN: 'LinkedIn',
  TXT_CHARGES: 'Charges',
  TXT_TYPE: 'Type',
  TXT_MINORDER: 'Minimum Order Value For Free Delivery',
  TXT_KEY: 'Key',
  TXT_SECRET: 'Secret',
  TXT_RESET_PASS:'Reset password',
  TXT_USERNAME: 'Username',
  TXT_LOGOUT:"Logout",


  ERROR_USERNAME: 'Please enter your username',
  ERROR_EMAIL: 'Please enter your email id',
  ERROR_PASSWORD: 'Please enter your password',
  ERROR_MOBILE: 'Please enter your mobile number',
  ERROR_FIRST_NAME: 'Please enter your first name',
  ERROR_LAST_NAME: 'Please enter your last name',
  ERROR_STORE_NAME: 'Please enter your store name',
  ERROR_ADDRESS: 'Please enter your address',
  ERROR_CITY: 'Please enter your city',
  ERROR_PINCODE: 'Please enter your pincode',
  ERROR_STATE: 'Please enter your state',
  ERROR_COUNTRY: 'Please enter your country',
  ERROR_DOMAIN: 'Please enter your domain',
  ERROR_CATEGORY: 'Please enter your category',
  ERROR_FACEBOOK: 'Please enter your facebook link',
  ERROR_LINKEDIN: 'Please enter your linkedin link',
  ERROR_CHARGES: 'Please enter your charges',
  ERROR_TYPE: 'Please enter your type',
  ERROR_MINORDER: 'Please enter your minimum order value',
  ERROR_KEY: 'Please enter your key',
  ERROR_SECRET: 'Please enter your secret',

  ERROR_EMAILV: 'Please enter valid email address',
  ERROR_PASSWORDV:
    'Password must be at least 5 characters long with atleast one symbol and one number',
  ERROR_MOBILEV: 'Please enter valid mobile number',

  PARAM_TITLE: 'title',

  USER_DATA: 'USER_DATA',

  FIREBASE_TOKEN: 'FIREBASE',
};
